name: life_at_iitk
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  async: ^2.5.0
  auto_route: ^3.0.3
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.5.4
  connectivity: ^3.0.3 
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  drift: ^1.0.1
  # dynamic_theme: ^1.0.1
  feature_discovery: ^0.14.0
  # firebase_analytics: ^8.0.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  firebase_messaging: ^10.0.9
  firebase_storage: ^10.0.6
  # flushbar: ^1.10.4
  another_flushbar: ^1.10.17
  fcm_config: ^3.1.3
  flutter_bloc: ^7.0.0
  # # flutter_datetime_picker: ^1.4.0/
  flutter_hooks: ^0.16.0
  # flutter_icons: ^1.1.
  # fluttericon: ^2.0.0
  flutter_vector_icons: ^1.0.0
  flutter_linkify: ^5.0.0
  flutter_local_notifications: ^9.0.1
  flutter_native_timezone: ^2.0.0
  flutter_redux: ^0.8.2
  flutter_slidable: ^0.6.0-nullsafety.0
  flutter_spinkit: ^5.0.0
  freezed_annotation: ^0.14.1
  get_it: ^7.2.0
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  http: ^0.13.1 
  image_picker: ^0.7.4 
  # implicitly_animated_reorderable_list: ^0.4.0-dev+4
  injectable: ^1.5.0
  intl: ^0.17.0
  mobx: ^2.0.1
  # moor: ^4.2.1
  network_to_file_image: ^3.0.3
  path: ^1.8.0
  path_provider: ^2.0.1 
  permission_handler: ^6.1.1
  photo_view: ^0.13.0
  provider: ^5.0.0
  qr_flutter: ^4.0.0
  rate_my_app: ^1.1.0+1
  redux: ^5.0.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5 
  # sqflite: ^2.0.0+3
  sqlite3_flutter_libs: ^0.4.1 
  table_calendar: ^3.0.0-nullsafety.1
  url_launcher: ^6.0.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.4
  drift_dev: ^1.0.2
  freezed: ^0.14.1+2
  hive_generator: ^1.0.1
  injectable_generator: ^1.2.2
  lint: ^1.5.3 
  # moor_generator: ^4.2.1 

flutter:
  uses-material-design: true
  assets:
    - assets/launch.png
    - assets/
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/Comfortaa/static/Comfortaa-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/Raleway/Raleway-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/Nunito/Nunito-Regular.ttf
